### ISSUE TITLE
Role fails to find local zimbra commands

### ISSUE THREAD

**Issue by YanChii** [lucascbeyeler/zimbra#11] opened 2017-09-26 20:41 UTC
Hi,

first of all, thank you for your effort putting together this role. It looks really good.
But I am having issue during the install (Centos 7 minimal) in this task:
```
TASK [lucascbeyeler.zimbra : Enabling SpamAssassin Auto Update] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "zmlocalconfig -e antispam_enable_rule_updates=true", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```
The problem is that the PATH variable is not being loaded and the task uses a relative path to the `zmlocalconfig` command.

Quick tests:
```
ansible localhost -m command -a "zmlocalconfig -e antispam_enable_rule_updates=true" -b --become-user=zimbra
localhost | FAILED | rc=2 >>
[Errno 2] No such file or directory
```
```
ansible localhost -m command -a "which zmlocalconfig" -b --become-user=zimbra
localhost | FAILED | rc=1 >>
which: no zmlocalconfig in (/sbin:/bin:/usr/sbin:/usr/bin)
```

Adding `/opt/zimbra/bin/` before the command seems to solve the problem.

Jan

**Comment by lucascbeyeler** [comment] 2017-09-27 19:35
Hello @YanChii,

Can you check if the problem persist? I made the changes to use the correct path for zmlocalconfig inside the file.

Regards,
Lucas Costa Beyeler

**Comment by YanChii** [comment] 2017-09-28 10:02
Now it works correctly.
Thank you!
Jan

**Comment by lucascbeyeler** [comment] 2017-09-28 12:51
I'm closing this issue, as the problem is already fixed. Have a nice day and thanks for your support.

Regards,
Lucas Costa Beyeler

**Closed by lucascbeyeler** 2017-09-28 12:51 UTC
Labels: bug
